## Data Loading and Exploration

In [32]:
import pandas as pd
df = pd.read_csv('balanced_hallucinations.csv')
df.head()

,reference,input,output,label,label_gpt-4o,explanation_gpt-4o,label_claude-3-5-sonnet-latest,explanation_claude-3-5-sonnet-latest,label_litellm/together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo,explanation_litellm/together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo,...,website,synthetic,language,hallucination_type_realized,question_type,hallucination_type_encouraged,hallucination_type_realized_ensemble,human_label,label_mistral-large-latest,explanation_mistral-large-latest
0,Los sitios web seguros .gov usan HTTPSUn canda...,Will the use of HTTPS on .gov websites be mand...,The US government has not announced a specific...,hallucinated,hallucinated,The query asks if the use of HTTPS on .gov web...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,factual,EXPLANATION: The reference text does not provi...,...,https://medlineplus.gov/,True,en,Outdated information hallucination,Out-of-scope information,Other hallucination,Outdatedness Hallucination,NaN,NaN,NaN
1,Experience Cloud uses the following hosts to d...,What specific domains should be allowed throug...,Adobe Experience Cloud uses the following host...,hallucinated,hallucinated,The query asks for specific domains that shoul...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The query asks for specific domai...,...,https://experienceleague.adobe.com/en/docs,True,en,Incompleteness hallucination,Out-of-scope information,Other hallucination,Incompleteness Hallucination,NaN,NaN,NaN
2,Programmatically perform administrative tasks ...,What can you use the Atlas Administration API ...,cally perform administrative tasks on Atlas cl...,hallucinated,hallucinated,The answer is incomplete and contains a typogr...,NaN,NaN,NaN,NaN,...,https://www.mongodb.com/docs/,True,en,NaN,NaN,NaN,Incompleteness Hallucination,NaN,factual,"LABEL: ""factual""\n\nEXPLANATION:\n1. The query..."
3,“Nutrient input from the Maumee River is the d...,What is an image that represents the Maumee Ri...,A plume of green algae spreading across the la...,hallucinated,hallucinated,The query asks for an image that represents th...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text does not provi...,...,https://earthobservatory.nasa.gov/,True,en,Unverifiable information hallucination,Multimodal content,Other hallucination,Unverifiability Hallucination,hallucinated,NaN,NaN
4,Alzheimer's disease and related dementias (AD/...,What specific breakthroughs in Alzheimer's tre...,"Based on current NIH research initiatives, sev...",hallucinated,hallucinated,The query asks about specific breakthroughs in...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text does not provi...,...,https://www.ncbi.nlm.nih.gov/,True,en,Overclaim hallucination,Out-of-scope information,Other hallucination,Unverifiability Hallucination,NaN,NaN,NaN

In [33]:
df.shape

(18254, 22)

In [34]:
df['hallucination_type_realized'].value_counts()

hallucination_type_realized
Relation-error hallucination              2513
Incompleteness hallucination              1938
Overclaim hallucination                   1520
Outdated information hallucination         838
Unverifiable information hallucination     821
Entity-error hallucination                 529
Name: count, dtype: int64

In [35]:
df['hallucination_type_realized_ensemble'].value_counts()

hallucination_type_realized_ensemble
Incompleteness Hallucination     2819
Unverifiability Hallucination    2707
Entity-error Hallucination       1628
Relation-error Hallucination      960
Overclaim Hallucination           744
Outdatedness Hallucination        252
Other hallucination                 4
Name: count, dtype: int64

In [36]:
df['label'].value_counts()

label
factual         9140
hallucinated    9114
Name: count, dtype: int64

In [37]:
df['synthetic'].value_counts()

synthetic
True     16058
False     2196
Name: count, dtype: int64

In [38]:
df['language'].value_counts()

language
en    18254
Name: count, dtype: int64

In [39]:
df['question_type'].value_counts()

question_type
Default question type                              5707
Advanced logical reasoning                         2201
Out-of-scope information                           2168
Multimodal content                                 2161
Other common hallucinated questions                2127
Errors, contradictions, or unsolvable questions    2122
Name: count, dtype: int64

In [40]:
df.isnull().sum()

reference                                                             0
input                                                                 0
output                                                               24
label                                                                 0
label_gpt-4o                                                          0
explanation_gpt-4o                                                   93
label_claude-3-5-sonnet-latest                                     1768
explanation_claude-3-5-sonnet-latest                               1768
label_litellm/together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo           1768
explanation_litellm/together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo     1768
rag_model                                                             0
force_even_split                                                      0
website                                                               0
synthetic                                                             0
language                                                              0
hallucination_type_realized                                       10095
question_type                                                      1768
hallucination_type_encouraged                                      1768
hallucination_type_realized_ensemble                               9140
human_label                                                       15087
label_mistral-large-latest                                        16486
explanation_mistral-large-latest                                  16486
dtype: int64

## Data Cleaning

In [41]:
#filter out undesired question types
clean_df = df[(df['question_type']=='Default question type') |
              (df['question_type']=='Other common hallucinated questions')]
clean_df.head()

,reference,input,output,label,label_gpt-4o,explanation_gpt-4o,label_claude-3-5-sonnet-latest,explanation_claude-3-5-sonnet-latest,label_litellm/together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo,explanation_litellm/together_ai/Qwen/Qwen2.5-7B-Instruct-Turbo,...,website,synthetic,language,hallucination_type_realized,question_type,hallucination_type_encouraged,hallucination_type_realized_ensemble,human_label,label_mistral-large-latest,explanation_mistral-large-latest
5,"A.D.A.M., Inc. estÃ¡ acreditada por la URAC, t...","What organization has accredited A.D.A.M., Inc...","A.D.A.M., Inc. is accredited by the Atlantis H...",hallucinated,hallucinated,The query asks which organization has accredit...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text clearly states...,...,https://medlineplus.gov/,True,en,Entity-error hallucination,Default question type,Entity-error hallucination,Relation-error Hallucination,NaN,NaN,NaN
8,"""This dataset for NOAA's Science On a Sphere d...",What type of educational activity is encourage...,The dataset encourages learners to complete a ...,hallucinated,hallucinated,The query asks about the type of educational a...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text mentions that ...,...,https://www.noaa.gov/research,True,en,Relation-error hallucination,Default question type,Relation-error hallucination,Unverifiability Hallucination,NaN,NaN,NaN
9,"Dimension items include ""Foreground"" and ""Back...",What is the primary reason for a hit to be cla...,The primary reason for a hit to be classified ...,hallucinated,hallucinated,The query asks for the primary reason a hit is...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text states that a ...,...,https://experienceleague.adobe.com/en/docs,True,en,Relation-error hallucination,Other common hallucinated questions,Other hallucination,Relation-error Hallucination,NaN,NaN,NaN
10,"Atlas Search runs a new process, called mongot...",What are the specific hardware requirements fo...,"Based on our production monitoring data, mongo...",hallucinated,hallucinated,The reference text provides information about ...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text does not provi...,...,https://www.mongodb.com/docs/,True,en,Unverifiable information hallucination,Other common hallucinated questions,Other hallucination,Overclaim Hallucination,NaN,NaN,NaN
21,The business implications are stark. In a surv...,What percentage of banking executives in the l...,34% of banking executives in the loan originat...,hallucinated,hallucinated,The query asks for the percentage of banking e...,hallucinated,EXPLANATION:\nLet's analyze this step by step:...,hallucinated,EXPLANATION: The reference text states that 34...,...,https://www.mongodb.com/docs/,True,en,Relation-error hallucination,Other common hallucinated questions,Other hallucination,Relation-error Hallucination,hallucinated,NaN,NaN

In [42]:
#omit irrelevant columns
clean_df = clean_df[['reference', 'input', 'output','label', 'hallucination_type_realized', 'question_type', 'hallucination_type_encouraged']]
clean_df.head()

,reference,input,output,label,hallucination_type_realized,question_type,hallucination_type_encouraged
5,"A.D.A.M., Inc. estÃ¡ acreditada por la URAC, t...","What organization has accredited A.D.A.M., Inc...","A.D.A.M., Inc. is accredited by the Atlantis H...",hallucinated,Entity-error hallucination,Default question type,Entity-error hallucination
8,"""This dataset for NOAA's Science On a Sphere d...",What type of educational activity is encourage...,The dataset encourages learners to complete a ...,hallucinated,Relation-error hallucination,Default question type,Relation-error hallucination
9,"Dimension items include ""Foreground"" and ""Back...",What is the primary reason for a hit to be cla...,The primary reason for a hit to be classified ...,hallucinated,Relation-error hallucination,Other common hallucinated questions,Other hallucination
10,"Atlas Search runs a new process, called mongot...",What are the specific hardware requirements fo...,"Based on our production monitoring data, mongo...",hallucinated,Unverifiable information hallucination,Other common hallucinated questions,Other hallucination
21,The business implications are stark. In a surv...,What percentage of banking executives in the l...,34% of banking executives in the loan originat...,hallucinated,Relation-error hallucination,Other common hallucinated questions,Other hallucination

In [43]:
#drop rows with missing values in output column
clean_df = clean_df[clean_df['output'].notna()]

In [44]:
#check missing values
clean_df.isnull().sum()

reference                           0
input                               0
output                              0
label                               0
hallucination_type_realized      5161
question_type                       0
hallucination_type_encouraged       0
dtype: int64

In [45]:
clean_df.shape

(7820, 7)

In [46]:
clean_df.to_csv('cleaned_data.csv', index=False)