### workflow:
1. remove duplicates of reference texts (removed as many as possible, some still exist)
2. establish baseline of performance by running BERTopic with default parameters -> creates too many topics
3. use zero-shot topic modeling to lower number of topics 
4. refine parameters
5. extract finalized topic assignments

In [2]:
import pandas as pd

docs = pd.read_csv('/Users/jamiewong/Documents/school/2025-26/ECS 111/AI-Hallucinations-Detection/data/cleaned_data.csv')['reference'].drop_duplicates()
len(docs)

4544

In [3]:
docs = docs[~docs.str.contains('the most informative paragraph:')] #removes a duplicate with LLM speech in the front
len(docs)

4543

## Unsupervised Topic Modeling

In [4]:
#pre-compute embeddings to speed up BERTopic
from sentence_transformers import SentenceTransformer

docs = docs.to_numpy()
sentence_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
embeddings = sentence_model.encode(docs, show_progress_bar=True)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/142 [00:00<?, ?it/s]

In [5]:
from umap import UMAP
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from bertopic import BERTopic

umap_model = UMAP(random_state=42) #set seed to present stochastic behavior in UMAP

#get english and spanish stop words
languages = ['english', 'spanish']
en_sp_stop_words = set()
for lang in languages:
    en_sp_stop_words.update(stopwords.words(lang))
en_sp_stop_words = list(en_sp_stop_words)

#vectorizer_model = CountVectorizer(stop_words="english")
vectorizer_model = CountVectorizer(stop_words=en_sp_stop_words)

topic_model = BERTopic(language = "multilingual",
                       umap_model = umap_model, #pass seeded model to BERTopic
                       nr_topics = "auto", #merges similar topics
                       vectorizer_model=vectorizer_model) #helps filter stop words
topics, probs = topic_model.fit_transform(docs, embeddings) #fit topic model using docs and pre-computed embeddings

In [6]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1062,-1_data_databricks_women_puede,"[data, databricks, women, puede, use, also, us...",[This get started article walks you through us...
1,0,943,0_data_mongodb_atlas_databricks,"[data, mongodb, atlas, databricks, search, tab...",[Garaudy Etienne joined MongoDB as a Product M...
2,1,480,1_credit_account_bank_financial,"[credit, account, bank, financial, accounts, m...","[However, checking accounts tend to pay low in..."
3,2,361,2_court_law_state_eff,"[court, law, state, eff, apr, supreme, courts,...","[""The single question presented by this record..."
4,3,297,3_noaa_education_program_science,"[noaa, education, program, science, environmen...",[NOAA brings thousands of K-12 teachers and st...
5,4,290,4_ice_storm_water_kilometers,"[ice, storm, water, kilometers, snow, miles, i...",[Tropical Storm Erika was quickly losing steam...
6,5,284,5_pcbs_cancer_health_care,"[pcbs, cancer, health, care, pcb, treatment, s...","[""This is part 4 of PyMongo Monday. Previously..."
7,6,138,6_puede_bacterias_pueden_infecciones,"[puede, bacterias, pueden, infecciones, enferm...",['El lupus es un tipo de enfermedad autoinmune...
8,7,124,7_pmc_nlm_journal_articles,"[pmc, nlm, journal, articles, pubmed, national...","[""PubMed Central® (PMC) is a free full-text ar..."
9,8,64,8_gov_https_official_websites,"[gov, https, official, websites, web, secure, ...",[Secure .gov websites use HTTPS\n\n ...
10,9,55,9_clouds_solar_sun_earth,"[clouds, solar, sun, earth, eclipse, moon, atm...","[On August 21, 2017, millions of Americans saw..."
11,10,48,10_abortion_court_roe_right,"[abortion, court, roe, right, fetus, pregnancy...",[Roe v. Wade is the Supreme Court case that he...
12,11,43,11_diabetes_glucosa_adults_type,"[diabetes, glucosa, adults, type, sangre, insu...",[Heart disease remains a major cause of morbid...
13,12,37,12_international_convention_management_marine,"[international, convention, management, marine...",[l legal framework for the conservation and ma...
14,13,30,13_nanoparticles_anticuerpos_immune_antibodies,"[nanoparticles, anticuerpos, immune, antibodie...",[A 96 well plate is coated with capture antibo...
15,14,26,14_paragraphs_sorry_paragraph_provide,"[paragraphs, sorry, paragraph, provide, text, ...","[I'm sorry, but it seems like the provided tex..."
16,15,26,15_crab_octonauts_ocean_episode,"[crab, octonauts, ocean, episode, urchins, fis...","[""Before we begin our chat, let’s set the stag..."
17,16,25,16_metastore_privilege_securable_catalog,"[metastore, privilege, securable, catalog, pri...",['A privilege is a right granted to a principa...
18,17,24,17_cli_atlas_install_telemetry,"[cli, atlas, install, telemetry, command, mong...",[You can also use the brew install mongodb-atl...
19,18,22,18_dimension_attribution_metric_model,"[dimension, attribution, metric, model, item, ...",[The ‘Marketing channel’ dimension functions i...
20,19,21,19_cannabis_health_public_legalization,"[cannabis, health, public, legalization, use, ...",[The landscape of cannabis legalization in the...
21,20,21,20_urac_salud_ethics_cumple,"[urac, salud, ethics, cumple, red, www, editor...","[A.D.A.M., Inc. estÃ¡ acreditada por la URAC, ..."
22,21,20,21_fire_fires_square_california,"[fire, fires, square, california, burn, drough...",[Unlike wildfires sparked by lightning or acci...
23,22,20,22_medlineplus_biblioteca_salud_nacionales,"[medlineplus, biblioteca, salud, nacionales, i...",[MedlinePlus es un servicio informativo en lín...
24,23,18,23_phytoplankton_blooms_chlorophyll_waters,"[phytoplankton, blooms, chlorophyll, waters, a...",[Chlorophyll is used by algae and other phytop...
25,24,16,24_covid_19_coronavirus_virus,"[covid, 19, coronavirus, virus, post, long, pr...",[Most people who have COVID-19 recover complet...
26,25,13,25_ab_initio_beginning_void,"[ab, initio, beginning, void, latin, used, mea...","[Ab initio is a Latin term that means ""from th..."
27,26,13,26_health_communication_synthesis_people,"[health, communication, synthesis, people, inf...","[""Health communication is an area where changi..."
28,27,11,27_academies_national_engineering_medicine,"[academies, national, engineering, medicine, a...",[Academies work together as the National Acade...
29,28,11,28_priori_assumption_acknowledgement_without,"[priori, assumption, acknowledgement, without,...",[An a priori assumption is an assumption that ...

In [7]:
topic_model.get_params()

{'calculate_probabilities': False,
 'ctfidf_model': ClassTfidfTransformer(),
 'embedding_model': None,
 'hdbscan_model': HDBSCAN(min_cluster_size=10, prediction_data=True),
 'language': 'multilingual',
 'low_memory': False,
 'min_topic_size': 10,
 'n_gram_range': (1, 1),
 'nr_topics': 'auto',
 'representation_model': None,
 'seed_topic_list': None,
 'top_n_words': 10,
 'umap_model': UMAP(n_jobs=1, random_state=42, tqdm_kwds={'bar_format': '{desc}: {percentage:3.0f}%| {bar} {n_fmt}/{total_fmt} [{elapsed}]', 'desc': 'Epochs completed', 'disable': True}),
 'vectorizer_model': CountVectorizer(stop_words=['against', 'estuvierais', 'tuviesen', 'sería',
                             'esa', 'habrías', 'suya', 'son', 'estábamos',
                             'también', 'más', 'nuestro', 'tuviese',
                             'themselves', 'hubiéramos', 'tuviste', 'seríais',
                             'very', 'will', 'desde', 'seréis', 'tenga',
                             "she'll", 'estuviésemos', 'her', 'estamos',
                             "they're", 'tuvieron', 'vosotros', 'so', ...]),
 'verbose': False,
 'zeroshot_min_similarity': 0.7,
 'zeroshot_topic_list': None}

In [8]:
hierarchical_topics = topic_model.hierarchical_topics(docs)
print(topic_model.get_topic_tree(hierarchical_topics))

100%|██████████| 28/28 [00:00<00:00, 810.05it/s]

.
├─atlas_data_mongodb_search_databricks
│    ├─atlas_data_mongodb_search_databricks
│    │    ├─atlas_data_mongodb_search_databricks
│    │    │    ├─■──cli_atlas_install_telemetry_command ── Topic: 17
│    │    │    └─■──data_mongodb_atlas_databricks_search ── Topic: 0
│    │    └─dimension_metastore_model_privilege_attribution
│    │         ├─■──metastore_privilege_securable_catalog_principal ── Topic: 16
│    │         └─■──dimension_attribution_metric_model_item ── Topic: 18
│    └─diabetes_puede_gov_cuerpo_salud
│         ├─diabetes_puede_cuerpo_bacterias_enfermedad
│         │    ├─puede_enfermedad_bacterias_pueden_infecciones
│         │    │    ├─■──covid_19_coronavirus_virus_post ── Topic: 24
│         │    │    └─■──puede_bacterias_pueden_infecciones_enfermedad ── Topic: 6
│         │    └─diabetes_glucosa_sangre_adults_type
│         │         ├─■──diabetes_glucosa_adults_type_sangre ── Topic: 11
│         │         └─■──nanoparticles_anticuerpos_immune_antibodies_cells ── Topic: 13
│         └─gov_https_official_websites_salud
│              ├─ab_initio_latin_term_priori
│              │    ├─■──ab_initio_beginning_void_latin ── Topic: 25
│              │    └─■──priori_assumption_acknowledgement_without_father ── Topic: 28
│              └─gov_https_official_websites_salud
│                   ├─gov_https_official_websites_web
│                   │    ├─■──paragraphs_sorry_paragraph_provide_text ── Topic: 14
│                   │    └─■──gov_https_official_websites_web ── Topic: 8
│                   └─salud_urac_medlineplus_ethics_cumple
│                        ├─■──medlineplus_biblioteca_salud_nacionales_institutos ── Topic: 22
│                        └─■──urac_salud_ethics_cumple_red ── Topic: 20
└─noaa_court_state_law_credit
     ├─noaa_court_law_credit_education
     │    ├─court_law_state_right_supreme
     │    │    ├─■──abortion_court_roe_right_fetus ── Topic: 10
     │    │    └─■──court_law_state_eff_apr ── Topic: 2
     │    └─noaa_credit_education_account_health
     │         ├─credit_account_health_bank_financial
     │         │    ├─pmc_nlm_journal_national_medicine
     │         │    │    ├─■──academies_national_engineering_medicine_academy ── Topic: 27
     │         │    │    └─■──pmc_nlm_journal_articles_pubmed ── Topic: 7
     │         │    └─credit_account_bank_financial_accounts
     │         │         ├─credit_account_bank_financial_accounts
     │         │         │    ├─■──credit_account_bank_financial_accounts ── Topic: 1
     │         │         │    └─health_pcbs_studies_cancer_evidence
     │         │         │         ├─■──pcbs_cancer_health_care_pcb ── Topic: 5
     │         │         │         └─■──health_communication_synthesis_people_information ── Topic: 26
     │         │         └─■──cannabis_health_public_legalization_use ── Topic: 19
     │         └─noaa_education_program_science_environmental
     │              ├─noaa_education_program_science_environmental
     │              │    ├─■──international_convention_management_marine_mpas ── Topic: 12
     │              │    └─■──noaa_education_program_science_environmental ── Topic: 3
     │              └─■──crab_octonauts_ocean_episode_urchins ── Topic: 15
     └─ice_storm_water_kilometers_snow
          ├─ice_storm_water_kilometers_snow
          │    ├─■──phytoplankton_blooms_chlorophyll_waters_algae ── Topic: 23
          │    └─ice_storm_water_kilometers_snow
          │         ├─■──ice_storm_water_kilometers_snow ── Topic: 4
          │         └─■──clouds_solar_sun_earth_eclipse ── Topic: 9
          └─■──fire_fires_square_california_burn ── Topic: 21

## Zero-shot Topic Modeling

In [9]:
from bertopic.representation import KeyBERTInspired
umap_model = UMAP(random_state=42)
zeroshot_topics = ['Business', 'Finance', 'Law', 'Technology','Science', 'Health']

topic_model2 = BERTopic(
    umap_model=umap_model,
    embedding_model="thenlper/gte-small", #recompute embeddings, throws error when using pre-computed ones
    min_topic_size=15,
    zeroshot_topic_list=zeroshot_topics,
    zeroshot_min_similarity=.75,
    representation_model=KeyBERTInspired(),
    vectorizer_model=vectorizer_model,
    nr_topics='auto'
)
topics, _ = topic_model2.fit_transform(docs)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [10]:
topic_model2.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,40,-1_pcbs_carcinogenic_diabetes_thyroid,"[pcbs, carcinogenic, diabetes, thyroid, tcdd, ...",[Complex technical mixtures of polychlorinated...
1,0,1086,Science,"[noaa, education, educational, environmental, ...","[The 21st CCLC program, the largest out-of-sch..."
2,1,865,Technology,"[databricks, mongodb, database, sql, data, atl...",['Databricks Apps lets developers create secur...
3,2,817,Finance,"[banking, banks, bank, deposits, savings, acco...",[Online banks offer many traditional bank serv...
4,3,665,Law,"[jurisdiction, judicial, court, courts, law, c...",[Most of the cases that the United States Supr...
5,4,626,Health,"[antioxidants, pregnancy, placebo, health, inm...",[Main results:\n \n \n We inc...
6,5,444,Business,"[databricks, data, database, tables, databases...",[This get started article walks you through us...

In [11]:
topic_model2.get_document_info(docs)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,"A.D.A.M., Inc. estÃ¡ acreditada por la URAC, t...",4,Health,"[antioxidants, pregnancy, placebo, health, inm...",[Main results:\n \n \n We inc...,antioxidants - pregnancy - placebo - health - ...,0.907601,False
1,"""This dataset for NOAA's Science On a Sphere d...",0,Science,"[noaa, education, educational, environmental, ...","[The 21st CCLC program, the largest out-of-sch...",noaa - education - educational - environmental...,0.922258,False
2,"Dimension items include ""Foreground"" and ""Back...",1,Technology,"[databricks, mongodb, database, sql, data, atl...",['Databricks Apps lets developers create secur...,databricks - mongodb - database - sql - data -...,0.876961,False
3,"Atlas Search runs a new process, called mongot...",1,Technology,"[databricks, mongodb, database, sql, data, atl...",['Databricks Apps lets developers create secur...,databricks - mongodb - database - sql - data -...,0.913095,False
4,The business implications are stark. In a surv...,5,Business,"[databricks, data, database, tables, databases...",[This get started article walks you through us...,databricks - data - database - tables - databa...,0.900787,False
...,...,...,...,...,...,...,...,...
4538,"La glucosa en la sangre, o azÃºcar en la sangr...",4,Health,"[antioxidants, pregnancy, placebo, health, inm...",[Main results:\n \n \n We inc...,antioxidants - pregnancy - placebo - health - ...,0.896686,False
4539,"Currently, Atlas Charts does not have any expe...",0,Science,"[noaa, education, educational, environmental, ...","[The 21st CCLC program, the largest out-of-sch...",noaa - education - educational - environmental...,0.878375,False
4540,'The National Oceanic and Atmospheric Administ...,0,Science,"[noaa, education, educational, environmental, ...","[The 21st CCLC program, the largest out-of-sch...",noaa - education - educational - environmental...,0.903129,False
4541,We are improving Natural Language mode to redu...,0,Science,"[noaa, education, educational, environmental, ...","[The 21st CCLC program, the largest out-of-sch...",noaa - education - educational - environmental...,0.868671,False
4542,'Create and deploy a Free cluster. You can use...,1,Technology,"[databricks, mongodb, database, sql, data, atl...",['Databricks Apps lets developers create secur...,databricks - mongodb - database - sql - data -...,0.915837,False

In [12]:
topic_model2.visualize_hierarchy(custom_labels=True)

In [13]:
topic_model2.get_document_info(docs).to_csv('topic_assignments.csv', index = False)